#!/bin/sh

if [ "${1}" = "--help" -o "${1}" = "-h" -o -z "${1}" ]; then
	echo "Useage :";
	echo "$ lenon <problem> [student] [timelimit] [score per problem]";
	echo '';
	echo "Config file (~/.lenonrc) example:";
	echo '    problem=lenon-test-problem';
	echo '    student=CSYZ27';
	echo '    time=0.1';
	echo '    score=120';
	exit;
fi

exec sh lenon-judge-main.sh $@ 2>/dev/null
